server:
  port: 8080

spring:
  mail:
    host: smtp.163.com
    username: 1XXXXXX@163.com
    password: XXXXXX
    to: 2XXXXXX@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

